"""init db and admin user table

Revision ID: 646c5c7c27ea
Revises: None
Create Date: 2016-06-09 15:52:59.221949

"""

# revision identifiers, used by Alembic.
revision = '646c5c7c27ea'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('username', sa.Unicode(length=20), nullable=False),
    sa.Column('email', sa.Unicode(length=50), nullable=True),
    sa.Column('encrypted_password', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_email')),
    sa.UniqueConstraint('username', name=op.f('uq_admin_username'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    ### end Alembic commands ###
